language: android
jdk: oraclejdk8
sudo: false
env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=18
    - ANDROID_BUILD_TOOLS_VERSION=28.0.2
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - QEMU_AUDIO_DRV=none
    - secure: cyT9jwPfDDoTPRxnoYf+agCBacUD0lHXbiiAcuUFfosu4kFkH2ja/J+kx3wVohZqDT5ZmUFuYhVwu1C2jdN7S7aDtMep6r5lWDtmBxK6iiF4DkHdLu7V0RT7XQjoeYIPcUhNTQQbpmjJbFbTYPaAx+2aiUeRU8/DGgawaUG9hy6LVXymmK1gIvMn4CepDrkhvGnOjqHOh1OG2bgDQUJx/1GiQf9VYOBEsyXHHqzMxoDQjIOAAEOOvKJQe3k+cFhVca3w3BUrO4EBuKbsuB8f/v5PYkGoeh+mKn3vXh0Eg8PvM2qwFJKhjxQ238aPNpVmUZl3FAVCPRudqEJeuFN6pPpE5Xh08zPk6c9MQDPbVWHGVixUgXOw+4o4RwWmblhoNYxQrGGFrHNRBpKHw1QgoNrJ6qqOu4Cc7/hCQnBYm91Bi7p+2aVxiQ0a0lWQTBBls6uVx0aO3v6NpbaVPjSTMxRyD/waL8/k38hi953IhUaKQLThtSORKXKMcDlV8YjqHBJeM9B4xHds1BHe49tFadWIuxApF5BQhAZS4bJnosjf0HjF3d7Ds5StHcVejOSq7W4dQNWR3b1mqmKbRUsMqL7TEa5mc5mtyIm1PISULzLLH0aQumunffBvILBsSLykVWUWnzPwddBl1XxJgPkJuQb7DwpmSIW7TGDdpaoCHWs=
    - secure: h04IBLuVU6sI4B/vfzaN3kypgzmZLt/kzBsGTZFiz2gyvDKk3UOd1DTCfHYbhdMrOMcQ58XyVfjwIR29tWTX8DCA911ej6HVXVIonur3AVXVcbN1f3lhNOoNt7m0hUUJYO8+fU1Q1clAZzt8cFOdKaNJBqOFQ9Sl+9I1ZmnVCWZDsfa4dqiok1xZEMJ6fE4yWqB14OAlFlSMcJJJ526RWZ7LKWN+5X2szOpxG5bIxU5b2eVdWj18myRs+sDKWAQBDJrezvQD33NWezFJxCaxmNPbac1k/Du3yjkENwvytWhq1JqLewTGA8ORPKZKeetaPV2mmMs3C1LXlavPZjyhl37ypQfxoqqsVGnkw6rR8gZtMDcL9dGZzVel7B6K2ztnEq8/Ep6EPvh3Uoo6yht9oLEtlUy4fyt8/uvMhDe8qWEAfqETfeCqE3WO5h1FX3Lunp4rTEi5HrBpCPfmz3d8hk/hWZnOJqT2cAMsDrt0c8htlTa6DwNrAR4yrZEAAvEXCgQcExpzreqY94fmxGxMEF9aool6o/kMLYSz2JXDeOlU1s8TBADAfYOmEsQwH2SmZ00sofPjUeXLKxQ+ahPUnLyC3tkUqg+IrM/Ft4CgRlcikqcaK4b5WAABE/Gj8uKLUGqgldUmWPUCzvHYy9l2odtNslQsvdM2YQRtgypFy34=
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
#- cd project-folder/
- chmod +x gradlew
- gem update --system
- gem install fastlane --no-rdoc --no-ri --no-document --quiet

script:
- ./gradlew test
- fastlane deploy_production
