language: android
jdk: oraclejdk8
sudo: required
dist: precise
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.2
  - android-28
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

script:
- "./gradlew build assembleRelease --no-daemon --stacktrace"
before_script:
- android list targets
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
after_success:
- sh set_tags.sh
deploy:
  provider: releases
  api_key:
    secure: iR13Xrbof2UqTUX6n4njfHaPMFt+j/hsnyXJ0OvLWcvEkjeDGuaxfmzwVXoXclkxeOVMDybxdzkzQswHmNnN/zInScTG7+t47axklsmrlzpcEZLifxOY9YMN239x2MNSbVvWsk+yaRU7qOJdmeYHpzKJq7cM/KlgX48nt6LPxtgRSraErYx3LKA/Uni8ZPLpNbuFoZv6qfYp+9BG9n1d2JGWAnCz3lxFy96cIEj7f1SHyPHkXVgZ4iTLMQw+51Mny6O2vA2N19Z4Px8Sya+2/WujCXvdE1lXWF9k/OWJmThSMslxiJ+emsJ1EektQbGhb+2jzKgd5RYubtFLvW0ebq2lfOt1X0qr4NNFOtFUxH0wU2WcPY0XMCWoFKjs63a0L/G9jN+pAxTtwwDOryOapbmadREdom1gC+X63bEDJ0A5E+Hc+BZdmWIn8GkhtOb1LgbliihqggrkGA2fh7nL49wzDTNsUZTVGrZXCFUwczSc8NdgzVoTekKrGsUIwDdLgul2YUp6lSW9Ch7aWI9I8F59dLBtTH+vZoBrdg/nwTHJiU+5XNdgsocy911U1oYj3v3xLENa3UkmUQhmXJSBTKb29ojziAj2g8NiUzFy+XddI27n8tVzERUXXtsBzGKJxZ/KQonPwUomcjFrlVSW0SxLcZ+aZ1cEaq0cDf5/m00=
  file: app/build/outputs/apk/yourapp*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: kambrish/demo_travis
