language: android
jdk:
- oraclejdk8
sudo: required

android:
  components:
  - tools
  - build-tools-28.0.2
  - android-28
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
before_install:
- cd project-folder/
- chmod +x gradlew
- gem update --system
- gem install fastlane --no-rdoc --no-ri --no-document --quiet

script:
- ./gradlew test
- fastlane deploy_production

notificati