# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a new version to the Google Play"
    lane :deploy_production do |options|
    puts options[:name]
    puts options[:tagname]
    git_name = options[:name]
    git_tagname = options[:tagname]

      gradle(task: "assembleRelease",
             properties: {
                 "android.injected.signing.store.file" => "keystore.jks",
                 "android.injected.signing.store.password" => "sourcefuse" ,
                 "android.injected.signing.key.alias" => "sourcefuse",
                 "android.injected.signing.key.password" => "sourcefuse",
                              })


      action set_github_release(
        repository_name: "kambrish/demo_travis",
        server_url: "https://api.github.com",
        api_token: "b58123494d18085d628c91305e023a33ee221e85",
        name:  git_name,
        tag_name: git_tagname,
        description: (File.read("changelog") rescue "No changelog provided"),
        commitish: "master",
        upload_assets: ["./app/build/outputs/apk/release/app-release.apk", "./app/build/outputs/apk/release/app-release.apk"]
      )
    end
end

